export const COMPONENT_ALIASES = {
    'USERS_MANAGEMENT': 'USERS_MANAGEMENT',
    'USERS_LIST': 'USERS_LIST',
    'SCALES_LIST': 'SCALES_LIST',
    'SCALES_MANAGEMENT': 'SCALES_MANAGEMENT',
    'HOME': 'HOME',
    'LOGIN': 'LOGIN',
    'SIGNUP': 'SIGNUP'
};